// src/topics/mustKnowQna/qnaData.js
const QNA = [
    {
        id: "q-001",
        q: "What is an operating system",
        a: "An operating system is the core software that manages hardware resources and provides services to programs.",
        tags: ["basics"],
    },
    {
        id: "q-002",
        q: "What is the kernel",
        a: "The kernel is the core part of the OS that runs with highest privilege and controls CPU, memory, devices, and files.",
        tags: ["kernel"],
    },
    {
        id: "q-003",
        q: "User mode vs kernel mode",
        a: "User mode has limited privileges. Kernel mode has full privileges to run sensitive instructions and access hardware.",
        tags: ["kernel", "basics"],
    },
    {
        id: "q-004",
        q: "What is a system call",
        a: "A system call is a controlled request from a program to the kernel for OS services like file I O, process control, or memory.",
        tags: ["kernel"],
    },
    {
        id: "q-005",
        q: "What is a process",
        a: "A process is a program in execution with its own address space and OS managed state.",
        tags: ["process"],
    },
    {
        id: "q-006",
        q: "What is a thread",
        a: "A thread is an execution unit inside a process. Threads share process memory but have separate stacks and registers.",
        tags: ["thread", "process"],
    },
    {
        id: "q-007",
        q: "Process vs thread in one line",
        a: "A process isolates memory, a thread shares memory inside a process.",
        tags: ["process", "thread"],
    },
    {
        id: "q-008",
        q: "What is a context switch",
        a: "Context switch is when the CPU saves state of one thread or process and loads state of another to resume execution.",
        tags: ["process", "thread", "scheduling"],
    },
    {
        id: "q-009",
        q: "Why context switching is costly",
        a: "It saves and restores registers, switches memory mappings, and can cause cache and TLB misses.",
        tags: ["scheduling", "performance"],
    },
    {
        id: "q-010",
        q: "Common process states",
        a: "New, Ready, Running, Waiting or Blocked, Terminated.",
        tags: ["process"],
    },

    {
        id: "q-011",
        q: "What is CPU scheduling",
        a: "CPU scheduling decides which ready process or thread runs next on the CPU.",
        tags: ["scheduling"],
    },
    {
        id: "q-012",
        q: "FCFS scheduling",
        a: "First Come First Serve runs processes in arrival order. Simple but can cause convoy effect.",
        tags: ["scheduling"],
    },
    {
        id: "q-013",
        q: "SJF scheduling",
        a: "Shortest Job First picks the smallest CPU burst first. It reduces average waiting time but needs burst prediction.",
        tags: ["scheduling"],
    },
    {
        id: "q-014",
        q: "Round Robin scheduling",
        a: "Round Robin gives each process a time quantum in rotation. It is common in time sharing systems.",
        tags: ["scheduling"],
    },
    {
        id: "q-015",
        q: "Priority scheduling",
        a: "Priority scheduling runs highest priority first. It can cause starvation without aging.",
        tags: ["scheduling"],
    },
    {
        id: "q-016",
        q: "Preemptive vs non preemptive scheduling",
        a: "Preemptive can interrupt a running task. Non preemptive waits until it blocks or finishes.",
        tags: ["scheduling"],
    },
    {
        id: "q-017",
        q: "Turnaround time",
        a: "Turnaround time is completion time minus arrival time.",
        tags: ["scheduling", "metrics"],
    },
    {
        id: "q-018",
        q: "Waiting time",
        a: "Waiting time is total time a process spends in the ready queue.",
        tags: ["scheduling", "metrics"],
    },
    {
        id: "q-019",
        q: "Response time",
        a: "Response time is time from request to first response. It matters in interactive systems.",
        tags: ["scheduling", "metrics"],
    },
    {
        id: "q-020",
        q: "Throughput",
        a: "Throughput is number of processes completed per unit time.",
        tags: ["metrics"],
    },

    {
        id: "q-021",
        q: "What is a race condition",
        a: "A race condition happens when output depends on timing of concurrent operations on shared data.",
        tags: ["sync"],
    },
    {
        id: "q-022",
        q: "What is a critical section",
        a: "A critical section is code that accesses shared data and must not run concurrently with other critical sections.",
        tags: ["sync"],
    },
    {
        id: "q-023",
        q: "What is mutual exclusion",
        a: "Mutual exclusion ensures only one thread enters a critical section at a time.",
        tags: ["sync"],
    },
    {
        id: "q-024",
        q: "Mutex vs semaphore",
        a: "A mutex is a binary lock with ownership. A semaphore is a counter used to control access to N resources.",
        tags: ["sync"],
    },
    {
        id: "q-025",
        q: "What is a deadlock",
        a: "Deadlock is when a set of processes are blocked forever, each waiting for a resource held by another.",
        tags: ["deadlock"],
    },
    {
        id: "q-026",
        q: "Four necessary conditions for deadlock",
        a: "Mutual exclusion, hold and wait, no preemption, circular wait.",
        tags: ["deadlock"],
    },
    {
        id: "q-027",
        q: "Deadlock prevention idea",
        a: "Break at least one necessary condition, like avoid hold and wait or enforce ordering to prevent circular wait.",
        tags: ["deadlock"],
    },
    {
        id: "q-028",
        q: "Deadlock avoidance idea",
        a: "Avoidance makes safe decisions using knowledge of future needs, like Bankers algorithm.",
        tags: ["deadlock"],
    },
    {
        id: "q-029",
        q: "Deadlock detection idea",
        a: "Detection finds cycles or unsafe waits, then recovery kills or rolls back processes.",
        tags: ["deadlock"],
    },
    {
        id: "q-030",
        q: "Starvation vs deadlock",
        a: "Starvation is indefinite delay due to unfair scheduling. Deadlock is circular waiting where none can proceed.",
        tags: ["deadlock", "scheduling"],
    },

    {
        id: "q-031",
        q: "What is virtual memory",
        a: "Virtual memory gives each process an illusion of large contiguous memory using paging and disk as backing store.",
        tags: ["memory"],
    },
    {
        id: "q-032",
        q: "Paging in one line",
        a: "Paging splits memory into fixed size pages and frames to simplify allocation and reduce external fragmentation.",
        tags: ["memory"],
    },
    {
        id: "q-033",
        q: "What is a page fault",
        a: "A page fault happens when a process accesses a page not in RAM. OS loads it from disk or maps it.",
        tags: ["memory"],
    },
    {
        id: "q-034",
        q: "What is a page table",
        a: "A page table maps virtual pages to physical frames and stores permissions and status bits.",
        tags: ["memory"],
    },
    {
        id: "q-035",
        q: "What is TLB",
        a: "TLB is a fast cache of recent virtual to physical translations to speed up address translation.",
        tags: ["memory", "performance"],
    },
    {
        id: "q-036",
        q: "Internal vs external fragmentation",
        a: "Internal is wasted space inside allocated blocks. External is free space split into small holes.",
        tags: ["memory"],
    },
    {
        id: "q-037",
        q: "Thrashing",
        a: "Thrashing is excessive paging where system spends more time swapping than executing due to low free memory.",
        tags: ["memory", "performance"],
    },
    {
        id: "q-038",
        q: "Segmentation in one line",
        a: "Segmentation divides memory into variable sized logical segments like code, data, stack.",
        tags: ["memory"],
    },
    {
        id: "q-039",
        q: "Paging vs segmentation",
        a: "Paging is fixed size and simpler. Segmentation matches logical structure but can cause external fragmentation.",
        tags: ["memory"],
    },
    {
        id: "q-040",
        q: "Copy on write",
        a: "Copy on write shares pages until a write occurs, then a private copy is made. Common after fork.",
        tags: ["memory", "process"],
    },

    {
        id: "q-041",
        q: "What is a file system",
        a: "A file system organizes data on storage using files, directories, metadata, and allocation structures.",
        tags: ["filesystem"],
    },
    {
        id: "q-042",
        q: "What is an inode",
        a: "An inode is metadata about a file like permissions, owner, size, and block pointers, not the file name.",
        tags: ["filesystem"],
    },
    {
        id: "q-043",
        q: "What is a file descriptor",
        a: "A file descriptor is a small integer handle used by a process to refer to an open file or socket.",
        tags: ["filesystem", "kernel"],
    },
    {
        id: "q-044",
        q: "Hard link vs soft link",
        a: "Hard link points to the same inode. Soft link is a separate file that points to a path name.",
        tags: ["filesystem"],
    },
    {
        id: "q-045",
        q: "Journaling file system",
        a: "Journaling logs metadata changes before applying them, helping recovery after crash or power loss.",
        tags: ["filesystem"],
    },
    {
        id: "q-046",
        q: "File permissions idea",
        a: "Permissions control read, write, execute for owner, group, others. OS enforces access checks.",
        tags: ["filesystem", "security"],
    },
    {
        id: "q-047",
        q: "Why delete is not instant sometimes",
        a: "Data blocks are freed but may not be overwritten immediately. Only references are removed first.",
        tags: ["filesystem"],
    },
    {
        id: "q-048",
        q: "What is buffering in I O",
        a: "Buffering stores data temporarily to reduce device access overhead and smooth speed differences.",
        tags: ["io"],
    },
    {
        id: "q-049",
        q: "Blocking vs non blocking I O",
        a: "Blocking waits until operation completes. Non blocking returns immediately and you check later.",
        tags: ["io"],
    },
    {
        id: "q-050",
        q: "Interrupts in one line",
        a: "An interrupt is a signal that pauses CPU briefly so OS can handle an event like I O completion.",
        tags: ["io"],
    },

    {
        id: "q-051",
        q: "What is IPC",
        a: "IPC is inter process communication like pipes, message queues, shared memory, sockets, signals.",
        tags: ["ipc"],
    },
    {
        id: "q-052",
        q: "Pipe",
        a: "A pipe is a unidirectional byte stream between processes, often used between parent and child.",
        tags: ["ipc"],
    },
    {
        id: "q-053",
        q: "Socket",
        a: "A socket is an endpoint for network communication. It can be used locally or over a network.",
        tags: ["ipc", "network"],
    },
    {
        id: "q-054",
        q: "Shared memory IPC",
        a: "Shared memory is fastest IPC but needs synchronization because multiple processes access same memory region.",
        tags: ["ipc", "sync"],
    },
    {
        id: "q-055",
        q: "What is a daemon",
        a: "A daemon is a background service process that runs without direct user interaction.",
        tags: ["process"],
    },
    {
        id: "q-056",
        q: "What is a zombie process",
        a: "A zombie is a terminated process that still has an entry because parent has not collected its exit status.",
        tags: ["process"],
    },
    {
        id: "q-057",
        q: "What is an orphan process",
        a: "An orphan is a process whose parent ended. It gets adopted by a system process.",
        tags: ["process"],
    },
    {
        id: "q-058",
        q: "What is fork",
        a: "Fork creates a new process by duplicating the current process. The child starts as a copy.",
        tags: ["process"],
    },
    {
        id: "q-059",
        q: "What is exec",
        a: "Exec replaces current process image with a new program while keeping same process id.",
        tags: ["process"],
    },
    {
        id: "q-060",
        q: "Kernel module",
        a: "A kernel module is a loadable component that extends kernel functionality like adding a driver.",
        tags: ["kernel"],
    },

    {
        id: "q-061",
        q: "Monolithic kernel",
        a: "Monolithic kernel runs most OS services in kernel space for speed, but failures can be more dangerous.",
        tags: ["kernel"],
    },
    {
        id: "q-062",
        q: "Microkernel",
        a: "Microkernel keeps minimal core in kernel and runs many services in user space for isolation.",
        tags: ["kernel"],
    },
    {
        id: "q-063",
        q: "Hybrid kernel",
        a: "Hybrid mixes both. Some services stay in kernel for performance, while keeping modular design ideas.",
        tags: ["kernel"],
    },
    {
        id: "q-064",
        q: "What is a device driver",
        a: "A driver is software that lets OS communicate with specific hardware in a safe and standard way.",
        tags: ["io", "kernel"],
    },
    {
        id: "q-065",
        q: "What is DMA",
        a: "DMA lets devices transfer data to or from memory without CPU moving each byte.",
        tags: ["io", "performance"],
    },
    {
        id: "q-066",
        q: "What is polling",
        a: "Polling is repeatedly checking device status. It wastes CPU compared to interrupts in many cases.",
        tags: ["io"],
    },
    {
        id: "q-067",
        q: "What is spooling",
        a: "Spooling queues I O output like print jobs so devices process tasks sequentially.",
        tags: ["io"],
    },
    {
        id: "q-068",
        q: "What is a buffer cache",
        a: "Buffer cache stores disk blocks in memory to speed up repeated reads and improve I O performance.",
        tags: ["io", "filesystem", "performance"],
    },
    {
        id: "q-069",
        q: "What is an LRU page replacement idea",
        a: "LRU replaces the page that has not been used for the longest time, approximating best future behavior.",
        tags: ["memory"],
    },
    {
        id: "q-070",
        q: "What is Belady anomaly",
        a: "In FIFO replacement, adding more frames can increase page faults. That is Belady anomaly.",
        tags: ["memory"],
    },

    {
        id: "q-071",
        q: "What is a scheduler time quantum",
        a: "Time quantum is fixed CPU time slice given to a task in Round Robin before preemption.",
        tags: ["scheduling"],
    },
    {
        id: "q-072",
        q: "Convoy effect",
        a: "Convoy effect is when one long job delays many short jobs in FCFS, increasing average waiting time.",
        tags: ["scheduling"],
    },
    {
        id: "q-073",
        q: "What is aging in scheduling",
        a: "Aging gradually increases priority of waiting tasks to reduce starvation.",
        tags: ["scheduling"],
    },
    {
        id: "q-074",
        q: "What is a ready queue",
        a: "Ready queue holds processes that are ready to run and are waiting for CPU.",
        tags: ["process", "scheduling"],
    },
    {
        id: "q-075",
        q: "What is a wait queue",
        a: "Wait queue holds processes blocked on I O or other events until the event completes.",
        tags: ["process", "io"],
    },
    {
        id: "q-076",
        q: "What is a spinlock",
        a: "A spinlock is a lock where thread keeps checking in a loop. Good only for very short waits.",
        tags: ["sync", "performance"],
    },
    {
        id: "q-077",
        q: "Semaphore types",
        a: "Binary semaphore acts like a lock. Counting semaphore controls access to multiple identical resources.",
        tags: ["sync"],
    },
    {
        id: "q-078",
        q: "Condition variable use",
        a: "Condition variable lets threads sleep until a condition is true, used with a mutex.",
        tags: ["sync"],
    },
    {
        id: "q-079",
        q: "What is priority inversion",
        a: "Low priority task holds a lock needed by high priority task, causing high priority to wait.",
        tags: ["sync", "scheduling"],
    },
    {
        id: "q-080",
        q: "How to reduce priority inversion",
        a: "Use priority inheritance or priority ceiling protocols so lock holder runs sooner.",
        tags: ["sync", "scheduling"],
    },

    {
        id: "q-081",
        q: "What is memory protection",
        a: "Memory protection prevents one process from accessing memory of another using hardware and OS checks.",
        tags: ["memory", "security"],
    },
    {
        id: "q-082",
        q: "What is address translation",
        a: "Address translation converts virtual address to physical address using page tables and TLB.",
        tags: ["memory"],
    },
    {
        id: "q-083",
        q: "What is swapping",
        a: "Swapping moves whole processes or pages to disk to free RAM, then brings them back when needed.",
        tags: ["memory"],
    },
    {
        id: "q-084",
        q: "Demand paging",
        a: "Demand paging loads pages into memory only when they are actually accessed.",
        tags: ["memory"],
    },
    {
        id: "q-085",
        q: "What is segmentation fault",
        a: "It is an invalid memory access detected by hardware memory protection, OS terminates the program.",
        tags: ["memory"],
    },
    {
        id: "q-086",
        q: "File allocation methods",
        a: "Common methods are contiguous, linked, and indexed allocation, each with tradeoffs.",
        tags: ["filesystem"],
    },
    {
        id: "q-087",
        q: "Why indexing helps in file systems",
        a: "Indexing allows direct access to blocks without scanning a linked list, improving random access.",
        tags: ["filesystem", "performance"],
    },
    {
        id: "q-088",
        q: "Disk scheduling SCAN idea",
        a: "SCAN moves head in one direction servicing requests, then reverses, like an elevator.",
        tags: ["io"],
    },
    {
        id: "q-089",
        q: "Disk scheduling C SCAN idea",
        a: "C SCAN services requests in one direction only, then jumps back to start, giving uniform wait times.",
        tags: ["io"],
    },
    {
        id: "q-090",
        q: "What is a bootloader",
        a: "Bootloader starts the system by loading the kernel into memory and transferring control to it.",
        tags: ["basics", "kernel"],
    },

    {
        id: "q-091",
        q: "What is a kernel panic",
        a: "Kernel panic is when the kernel detects a fatal error and stops to avoid further damage or corruption.",
        tags: ["kernel"],
    },
    {
        id: "q-092",
        q: "Why do we need interrupts",
        a: "Interrupts let CPU respond to events like I O completion without wasting time polling devices.",
        tags: ["io"],
    },
    {
        id: "q-093",
        q: "What is multitasking",
        a: "Multitasking runs multiple tasks by rapidly switching CPU between them, giving illusion of parallelism.",
        tags: ["basics", "scheduling"],
    },
    {
        id: "q-094",
        q: "What is multiprocessing",
        a: "Multiprocessing uses multiple CPU cores to run tasks truly in parallel.",
        tags: ["basics", "performance"],
    },
    {
        id: "q-095",
        q: "What is multithreading",
        a: "Multithreading runs multiple threads inside a process to improve responsiveness and utilize cores.",
        tags: ["thread", "performance"],
    },
    {
        id: "q-096",
        q: "Why locks reduce performance",
        a: "Locks serialize work and add waiting. Too many locks can cause contention and context switches.",
        tags: ["sync", "performance"],
    },
    {
        id: "q-097",
        q: "What is a critical resource",
        a: "A critical resource is shared data or device that must be accessed in a controlled way.",
        tags: ["sync", "basics"],
    },
    {
        id: "q-098",
        q: "What is the purpose of system calls",
        a: "System calls provide a safe interface for programs to request privileged OS operations.",
        tags: ["kernel"],
    },
    {
        id: "q-099",
        q: "Why OS uses protection rings",
        a: "Protection rings limit damage by isolating user code from privileged kernel operations.",
        tags: ["security", "kernel"],
    },
    {
        id: "q-100",
        q: "Best quick way to answer OS questions",
        a: "Identify the resource involved - CPU, memory, disk, device - then explain what the kernel does to manage it.",
        tags: ["basics"],
    },
];

export default QNA;
